Less temporary memory allocations & share AF data when possible
omf2097/openomf pull request #632
Opened 2024-10-07 04:05 UTC by Vagabond

This needs somewhat careful review, especially the string parser changes.

2024-10-07 06:42 UTC, katajakasa commented on src/game/gui/textslider.c
> +        snprintf(tb->txt + off, sizeof(tb->txt) - off, "%s", "OFF");
I dislike this -- the idea with str type is that we can later convert it to utf-8. This is taking steps backwards. How about we cache the str to textslider instead ?

2024-10-09 21:01 UTC, katajakasa commented
I think we can close this now ?

2024-10-10 15:09 UTC, Vagabond commented
no, I think there's still some valid changes here, and maybe a broader discussion about when we should be using `str`

2024-10-10 18:16 UTC, katajakasa commented
> no, I think there's still some valid changes here, and maybe a broader discussion about when we should be using `str`

Okay. I'll start then :) I'd rather use the str whenever it comes to text, since it abstracts away the buffer length management and makes the code look a bit easier to read. snprintf and friends especially make it really hard to read (or properly understand!) the code :/

2024-11-26 06:59 UTC, Nopey requested changes
scene.c fighter de-duplication is a neat shortcut, seems worthwhile.

script.c  changes reduce number of extremely small stack based strings we create from slices, but no longer effects allocator pressure. Unsure if text slider changes are still relevant, but maybe?

replacing str usage with snprintf is icky, especially after katajakasa added the small string optimization.. *checks commit log* a few hours after this PR was opened? x)

2024-11-26 06:59 UTC, Nopey commented on src/formats/script.c
> +        if(strncmp(src->data + *now, "usw", m) == 0 && find_numeric_span(src, *now + m) > *now + m) {
```suggestion
        if(strncmp(str_c(src) + *now, "usw", 3) == 0 && find_numeric_span(src, *now + m) > *now + m) {
```
The strncmp call should compare all 3 characters like the str_equal_c did before, not just the first m.

2024-11-26 06:59 UTC, Nopey commented on src/utils/str.h
> +bool str_to_int(const str *string, size_t offset, int *m);
Please document the new `offset` param.

2024-11-26 06:59 UTC, Nopey commented on src/utils/str.c
> +    *result = strtol(string->data + pos, &end, 10);
Please bounds-check `pos` (aka `offset`) param, at least with an assert()

2024-11-26 06:59 UTC, Nopey commented on src/game/gui/textslider.c
> +static void render_text(component *c) {
Please rename this method to something that does not contain the word "render."

textslider_format? textslider_updatestr?

2025-04-07 16:53 UTC, katajakasa commented
Probably deprecated now ? textslider stuff is fixed with the text objects, and srt should use a small stack buffer for the small text objects.

2025-04-07 16:59 UTC, Vagabond commented
We can kill this.

2025-04-07 16:59 UTC, closed without merging