Various UI and lobby fixes
omf2097/openomf pull request #745
Opened 2024-11-04 20:18 UTC by Vagabond

See commits for details.

2024-11-04 20:26 UTC, katajakasa submitted a review, later dismissed
lgtm.

2024-11-05 00:37 UTC, Nopey requested changes
label_create_with_width change regresses kreissack toopathetic dialog

2024-11-05 00:37 UTC, Nopey commented on src/game/gui/label.c
> +    component_set_size_hints(c, width * tsize , h * 8);
`text_find_max_strlen` returns the length of the first line of wrapped text, not the maximum length of any line of text.

Perhaps text_find_line_count needs to be modified to also provide the caller with the longest line's length?

2024-11-05 00:37 UTC, Nopey commented on src/utils/str.c
> +    if(size != dst->len) {
```suggestion
    if(size == dst->len) {
        return;
    }
```

2024-11-05 17:40 UTC, Nopey commented on testing/test_text_render.c
> +    CU_ASSERT_EQUAL(2, longest);
The last line of this test's text will be more than 2 characters long

2024-11-05 17:43 UTC, Nopey commented on testing/test_text_render.c
> +    CU_ASSERT_EQUAL(2, longest);
wait no im still waking up that's not real

2024-11-05 17:44 UTC, Nopey commented
changes look like kreissack's dialog should still work, just gonna spin up the game rq

2024-11-05 17:47 UTC, Nopey commented
![image](https://github.com/user-attachments/assets/3a073bad-019c-4603-bb2e-7eedae07566c)
yeah, kreissack's good

2024-11-05 17:54 UTC, merged